generalized callBashScript() function

diff --git a/electron-async-test/binaries/test2 b/electron-async-test/binaries/test2
--- a/electron-async-test/binaries/test2
+++ b/electron-async-test/binaries/test2
@@ -1,9 +1,14 @@
 #!/bin/bash
 
 echo "Start of bash script test2"
+
+echo "\$1 is now $1"
+echo "\$2 is now $2"
+echo "\$3 is now $3"
+
 echo "This is an error" >&2
+
 echo "Sleep now for 3 seconds"
 sleep 3
 echo "Finished sleeping"
-echo "Exit now with error code 1"
-exit 1
+echo "There was an error! Exit now with code 1" >&2 && exit 1
diff --git a/electron-async-test/binaries/test3 b/electron-async-test/binaries/test3
--- a/electron-async-test/binaries/test3
+++ b/electron-async-test/binaries/test3
@@ -1,4 +1,12 @@
 #!/bin/bash
 
 echo "Start of bash script test3"
-echo "Finish of bash script test3"
+
+echo "\$1 is now $1"
+echo "\$2 is now $2"
+echo "\$3 is now $3"
+
+echo "This is an error" >&2
+
+echo "Exit now with code 0"
+exit 0
